# Generated by Django 3.1.4 on 2020-12-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=16)),
                ('price_range', models.FloatField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('long', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
